name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Release
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: '@klarna/aps-evaluator'
  publish:
    needs: release
    runs-on: ubuntu-latest
    if: ${{ needs.release.outputs.created }}
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Volta and Node.js
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts

      - name: Build
        run: yarn build

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
          provenance: true
