name: Publish to npm

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Volta and Node.js
        uses: volta-cli/action@v4

      - name: Install Dependencies
        run: yarn --frozen-lockfile --non-interactive --silent --ignore-scripts

      - name: Build
        run: yarn build

      - name: Publish to NPM
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
          provenance: true

      - name: Create release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.publish.outputs.version }}
          release_name: ${{ steps.publish.outputs.version }}
          body: ${{ steps.publish.outputs.version }}
          draft: true
          prerelease: false
