name: Pull request workflow

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Volta and Node.js
        uses: volta-cli/action@v1

      - name: Install Dependencies
        run: yarn install

      - name: Run linter
        run: yarn lint

      - name: Run tests
        run: yarn lint && yarn test
